import type { Artist, Portfolio, GalleryItem, Testimonial, Appointment } from "./types"

export const mockArtists: Artist[] = [
  {
    id: 1,
    name: "Carlos Mendoza",
    email: "carlos@inskpire.com",
    phone: "+1-555-0101",
    bio: "Especialista en tatuajes realistas y retratos. Más de 8 años creando arte en la piel con técnicas avanzadas de sombreado.",
    specialties: ["Realismo", "Retratos", "Blanco y Negro"],
    image_url: "/carlos.jpg?height=400&width=400",
    instagram_handle: "@carlos_ink",
    years_experience: 8,
    created_at: new Date("2023-01-01"),
    updated_at: new Date("2023-01-01"),
  },
  {
    id: 2,
    name: "Sofia Rodriguez",
    email: "sofia@inskpire.com",
    phone: "+1-555-0102",
    bio: "Artista especializada en tatuajes tradicionales y neo-tradicionales. Amante de los colores vibrantes y diseños únicos.",
    specialties: ["Tradicional", "Neo-tradicional", "Color"],
    image_url: "/sofia.jpg?height=400&width=400",
    instagram_handle: "@sofia_tattoos",
    years_experience: 6,
    created_at: new Date("2023-01-01"),
    updated_at: new Date("2023-01-01"),
  },
  {
    id: 3,
    name: "Miguel Torres",
    email: "miguel@inskpire.com",
    phone: "+1-555-0103",
    bio: "Experto en tatuajes geométricos y minimalistas. Creador de diseños únicos con líneas precisas y conceptos modernos.",
    specialties: ["Geométrico", "Minimalista", "Línea fina"],
    image_url: "/miguel.jpg?height=400&width=400",
    instagram_handle: "@miguel_geometric",
    years_experience: 5,
    created_at: new Date("2023-01-01"),
    updated_at: new Date("2023-01-01"),
  },
  {
    id: 4,
    name: "Ana Vega",
    email: "ana@inskpire.com",
    phone: "+1-555-0104",
    bio: "Maestra del blackwork y dotwork. Especializada en mandalas y diseños ornamentales con técnicas ancestrales.",
    specialties: ["Blackwork", "Dotwork", "Ornamental"],
    image_url: "/anaa.webp?height=400&width=400",
    instagram_handle: "@ana_blackwork",
    years_experience: 7,
    created_at: new Date("2023-01-01"),
    updated_at: new Date("2023-01-01"),
  },
  {
    id: 5,
    name: "Diego Morales",
    email: "diego@inskpire.com",
    phone: "+1-555-0105",
    bio: "Especialista en tatuajes japoneses tradicionales y new school. Fusiona técnicas clásicas con elementos modernos.",
    specialties: ["Japonés", "New School", "Oriental"],
    image_url: "/diego.jpg?height=400&width=400",
    instagram_handle: "@diego_japanese",
    years_experience: 9,
    created_at: new Date("2023-01-01"),
    updated_at: new Date("2023-01-01"),
  },
  {
    id: 6,
    name: "Luna Castillo",
    email: "luna@inskpire.com",
    phone: "+1-555-0106",
    bio: "Especialista en tatuajes femeninos delicados, fine line y acuarela. Crea diseños únicos con toques artísticos.",
    specialties: ["Fine Line", "Acuarela", "Femenino"],
    image_url: "/lunaa.jpg?height=400&width=400",
    instagram_handle: "@luna_fineline",
    years_experience: 4,
    created_at: new Date("2023-01-01"),
    updated_at: new Date("2023-01-01"),
  },
]

export const mockPortfolios: (Portfolio & {
  artist_name?: string
  instagram_handle?: string
  artist_image?: string
  price_range?: string
  duration_hours?: number
  difficulty?: "Fácil" | "Medio" | "Difícil" | "Experto"
  body_part?: string
  size?: "Pequeño" | "Mediano" | "Grande" | "Extra Grande"
})[] = [
  // Carlos Mendoza - Realismo (20 trabajos)
  {
    id: 1,
    artist_id: 1,
    title: "León Majestuoso",
    description: "Retrato realista de león con melena detallada en brazo completo",
    image_url: "/Leon.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["león", "realismo", "brazo", "animal", "melena"],
    created_at: new Date("2023-12-01"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$80.000-$120.000",
    duration_hours: 8,
    difficulty: "Experto",
    body_part: "Brazo",
    size: "Grande",
  },
  {
    id: 2,
    artist_id: 1,
    title: "Retrato Familiar",
    description: "Retrato realista de familia en espalda completa con técnica fotográfica",
    image_url: "/retrato.jpg?height=600&width=400",
    category: "Retratos",
    tags: ["familia", "retrato", "espalda", "fotográfico", "emocional"],
    created_at: new Date("2023-11-28"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$150.000-200.000",
    duration_hours: 12,
    difficulty: "Experto",
    body_part: "Espalda",
    size: "Extra Grande",
  },
  {
    id: 3,
    artist_id: 1,
    title: "Ojo Hiperrealista",
    description: "Tatuaje de ojo con lágrima en técnica hiperrealista",
    image_url: "/Ojos.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["ojo", "hiperrealista", "lágrima", "detalle", "expresivo"],
    created_at: new Date("2023-12-10"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$30.000-50.000",
    duration_hours: 4,
    difficulty: "Difícil",
    body_part: "Antebrazo",
    size: "Mediano",
  },
  {
    id: 4,
    artist_id: 1,
    title: "Lobo Aullando",
    description: "Lobo realista aullando a la luna con paisaje nocturno",
    image_url: "/lobo.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["lobo", "luna", "nocturno", "paisaje", "aullido"],
    created_at: new Date("2023-11-25"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$60.000-90.000",
    duration_hours: 6,
    difficulty: "Difícil",
    body_part: "Muslo",
    size: "Grande",
  },
  {
    id: 5,
    artist_id: 1,
    title: "Retrato de Mascota",
    description: "Retrato emotivo de perro en memoria, técnica realista",
    image_url: "/mascotas.jpeg?height=600&width=400",
    category: "Retratos",
    tags: ["mascota", "perro", "memoria", "emotivo", "homenaje"],
    created_at: new Date("2023-12-05"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$40.000-60.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Pantorrilla",
    size: "Mediano",
  },
  {
    id: 6,
    artist_id: 1,
    title: "Tigre Siberiano",
    description: "Retrato realista de tigre con pelaje detallado",
    image_url: "/tigre.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["tigre", "siberiano", "pelaje", "felino", "salvaje"],
    created_at: new Date("2023-11-20"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$70.000-100.000",
    duration_hours: 7,
    difficulty: "Experto",
    body_part: "Espalda",
    size: "Grande",
  },
  {
    id: 7,
    artist_id: 1,
    title: "Manos Entrelazadas",
    description: "Manos realistas entrelazadas simbolizando unión",
    image_url: "/manos.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["manos", "entrelazadas", "unión", "amor", "realista"],
    created_at: new Date("2023-11-15"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$350.000-550.000",
    duration_hours: 4,
    difficulty: "Medio",
    body_part: "Antebrazo",
    size: "Mediano",
  },
  {
    id: 8,
    artist_id: 1,
    title: "Reloj Vintage",
    description: "Reloj de bolsillo vintage con engranajes visibles",
    image_url: "/Relojj.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["reloj", "vintage", "engranajes", "tiempo", "mecánico"],
    created_at: new Date("2023-11-10"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$50.000-70.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Pecho",
    size: "Mediano",
  },
  {
    id: 9,
    artist_id: 1,
    title: "Rosa Realista",
    description: "Rosa hiperrealista con gotas de rocío",
    image_url: "/Rosa.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["rosa", "rocío", "naturaleza", "delicado", "femenino"],
    created_at: new Date("2023-11-05"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$250.000-400.000",
    duration_hours: 3,
    difficulty: "Medio",
    body_part: "Hombro",
    size: "Pequeño",
  },
  {
    id: 10,
    artist_id: 1,
    title: "Águila Real",
    description: "Águila real en vuelo con plumas detalladas",
    image_url: "/Aguila.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["águila", "vuelo", "plumas", "libertad", "majestuoso"],
    created_at: new Date("2023-10-30"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$80.000-110.000",
    duration_hours: 8,
    difficulty: "Experto",
    body_part: "Espalda",
    size: "Grande",
  },

  // Sofia Rodriguez - Tradicional/Neo-tradicional (15 trabajos)
  {
    id: 11,
    artist_id: 2,
    title: "Rosa Tradicional",
    description: "Rosa tradicional americana con banner y lettering",
    image_url: "/rosa tra.jpg?height=600&width=400",
    category: "Tradicional",
    tags: ["rosa", "tradicional", "banner", "lettering", "clásico"],
    created_at: new Date("2023-12-08"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$200.000-350.000",
    duration_hours: 3,
    difficulty: "Medio",
    body_part: "Antebrazo",
    size: "Mediano",
  },
  {
    id: 12,
    artist_id: 2,
    title: "Calavera Mexicana",
    description: "Calavera neo-tradicional con flores y colores vibrantes",
    image_url: "/calabera.jpg?height=600&width=400",
    category: "Neo-tradicional",
    tags: ["calavera", "mexicana", "flores", "colores", "día de muertos"],
    created_at: new Date("2023-12-03"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$400.000-600.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Muslo",
    size: "Grande",
  },
  {
    id: 13,
    artist_id: 2,
    title: "Pin-up Vintage",
    description: "Pin-up girl estilo años 50 con colores pastel",
    image_url: "/pin up.jpg?height=600&width=400",
    category: "Tradicional",
    tags: ["pin-up", "vintage", "años 50", "pastel", "retro"],
    created_at: new Date("2023-11-28"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$500.000-750.000",
    duration_hours: 6,
    difficulty: "Difícil",
    body_part: "Brazo",
    size: "Grande",
  },
  {
    id: 14,
    artist_id: 2,
    title: "Ancla Náutica",
    description: "Ancla tradicional con cuerda y elementos marinos",
    image_url: "/ancla.jpg?height=600&width=400",
    category: "Tradicional",
    tags: ["ancla", "náutico", "cuerda", "marino", "sailor"],
    created_at: new Date("2023-11-22"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$250.000-400.000",
    duration_hours: 3,
    difficulty: "Fácil",
    body_part: "Antebrazo",
    size: "Mediano",
  },
  {
    id: 15,
    artist_id: 2,
    title: "Corazón Sagrado",
    description: "Corazón sagrado con llamas y elementos religiosos",
    image_url: "/corazonl.jpg?height=600&width=400",
    category: "Tradicional",
    tags: ["corazón", "sagrado", "religioso", "llamas", "fe"],
    created_at: new Date("2023-11-18"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$300.000-450.000",
    duration_hours: 4,
    difficulty: "Medio",
    body_part: "Pecho",
    size: "Mediano",
  },

  // Miguel Torres - Geométrico/Minimalista (15 trabajos)
  {
    id: 16,
    artist_id: 3,
    title: "Mandala Sagrado",
    description: "Mandala geométrico con patrones perfectos y simetría",
    image_url: "/mandalas.jpg?height=600&width=400",
    category: "Geométrico",
    tags: ["mandala", "geométrico", "simetría", "sagrado", "patrón"],
    created_at: new Date("2023-12-06"),
    artist_name: "Miguel Torres",
    instagram_handle: "@miguel_geometric",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$400.000-650.000",
    duration_hours: 6,
    difficulty: "Difícil",
    body_part: "Espalda",
    size: "Grande",
  },
  {
    id: 17,
    artist_id: 3,
    title: "Montañas Minimalistas",
    description: "Paisaje de montañas en líneas finas y precisas",
    image_url: "/montaña.jpeg?height=600&width=400",
    category: "Minimalista",
    tags: ["montañas", "minimalista", "líneas", "paisaje", "naturaleza"],
    created_at: new Date("2023-12-01"),
    artist_name: "Miguel Torres",
    instagram_handle: "@miguel_geometric",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$150.000-250.000",
    duration_hours: 2,
    difficulty: "Fácil",
    body_part: "Antebrazo",
    size: "Pequeño",
  },
  {
    id: 18,
    artist_id: 3,
    title: "Cubo Imposible",
    description: "Ilusión óptica de cubo imposible en 3D",
    image_url: "/cubo.jpg?height=600&width=400",
    category: "Geométrico",
    tags: ["cubo", "ilusión", "3d", "imposible", "óptica"],
    created_at: new Date("2023-11-25"),
    artist_name: "Miguel Torres",
    instagram_handle: "@miguel_geometric",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$200.000-350.000",
    duration_hours: 3,
    difficulty: "Medio",
    body_part: "Brazo",
    size: "Mediano",
  },

  // Ana Vega - Blackwork/Dotwork (15 trabajos)
  {
    id: 19,
    artist_id: 4,
    title: "Mandala Blackwork",
    description: "Mandala complejo en técnica blackwork pura",
    image_url: "/blblb.jpg?height=600&width=400",
    category: "Blackwork",
    tags: ["mandala", "blackwork", "complejo", "negro", "ornamental"],
    created_at: new Date("2023-12-04"),
    artist_name: "Ana Vega",
    instagram_handle: "@ana_blackwork",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$500.000-800.000",
    duration_hours: 7,
    difficulty: "Experto",
    body_part: "Espalda",
    size: "Grande",
  },
  {
    id: 20,
    artist_id: 4,
    title: "Flor Dotwork",
    description: "Flor de loto en técnica dotwork con degradados",
    image_url: "/flor de loto.jpg?height=600&width=400",
    category: "Dotwork",
    tags: ["loto", "dotwork", "degradado", "puntos", "zen"],
    created_at: new Date("2023-11-30"),
    artist_name: "Ana Vega",
    instagram_handle: "@ana_blackwork",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$300.000-500.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Hombro",
    size: "Mediano",
  },

  // Diego Morales - Japonés/New School (15 trabajos)
  {
    id: 21,
    artist_id: 5,
    title: "Dragón Japonés",
    description: "Dragón tradicional japonés con nubes y viento",
    image_url: "/dragon.jpg?height=600&width=400",
    category: "Japonés",
    tags: ["dragón", "japonés", "nubes", "viento", "tradicional"],
    created_at: new Date("2023-12-02"),
    artist_name: "Diego Morales",
    instagram_handle: "@diego_japanese",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$1.000.000-1.500.000",
    duration_hours: 10,
    difficulty: "Experto",
    body_part: "Brazo completo",
    size: "Extra Grande",
  },
  {
    id: 22,
    artist_id: 5,
    title: "Koi New School",
    description: "Pez koi en estilo new school con colores vibrantes",
    image_url: "/koi.jpg?height=600&width=400",
    category: "New School",
    tags: ["koi", "new school", "vibrante", "pez", "agua"],
    created_at: new Date("2023-11-27"),
    artist_name: "Diego Morales",
    instagram_handle: "@diego_japanese",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$400.000-650.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Pantorrilla",
    size: "Grande",
  },

  // Luna Castillo - Fine Line/Acuarela (15 trabajos)
  {
    id: 23,
    artist_id: 6,
    title: "Flores Fine Line",
    description: "Ramo de flores delicadas en técnica fine line",
    image_url: "/linea fina.jpg?height=600&width=400",
    category: "Fine Line",
    tags: ["flores", "fine line", "delicado", "femenino", "elegante"],
    created_at: new Date("2023-12-07"),
    artist_name: "Luna Castillo",
    instagram_handle: "@luna_fineline",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$200.000-350.000",
    duration_hours: 3,
    difficulty: "Medio",
    body_part: "Costilla",
    size: "Mediano",
  },
  {
    id: 24,
    artist_id: 6,
    title: "Mariposa Acuarela",
    description: "Mariposa con efecto acuarela y colores suaves",
    image_url: "/acuarela.jpg?height=600&width=400",
    category: "Acuarela",
    tags: ["mariposa", "acuarela", "colores", "suave", "artístico"],
    created_at: new Date("2023-11-29"),
    artist_name: "Luna Castillo",
    instagram_handle: "@luna_fineline",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$300.000-450.000",
    duration_hours: 4,
    difficulty: "Difícil",
    body_part: "Hombro",
    size: "Mediano",
  },

  // Trabajos adicionales para llegar a 60+ trabajos
  {
    id: 25,
    artist_id: 1,
    title: "Búho Realista",
    description: "Búho nocturno con plumas detalladas y ojos penetrantes",
    image_url: "/buhoo.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["búho", "nocturno", "plumas", "ojos", "sabiduría"],
    created_at: new Date("2023-10-25"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$600.000-850.000",
    duration_hours: 6,
    difficulty: "Difícil",
    body_part: "Muslo",
    size: "Grande",
  },
  {
    id: 26,
    artist_id: 2,
    title: "Golondrina Tradicional",
    description: "Golondrina en vuelo estilo tradicional americano",
    image_url: "/golondrina.jpg?height=600&width=400",
    category: "Tradicional",
    tags: ["golondrina", "vuelo", "tradicional", "libertad", "viaje"],
    created_at: new Date("2023-10-20"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$180.000-280.000",
    duration_hours: 2,
    difficulty: "Fácil",
    body_part: "Cuello",
    size: "Pequeño",
  },
  {
    id: 27,
    artist_id: 3,
    title: "Constelación",
    description: "Constelación de estrellas conectadas minimalista",
    image_url: "/constelacion.jpg?height=600&width=400",
    category: "Minimalista",
    tags: ["constelación", "estrellas", "cosmos", "conexión", "destino"],
    created_at: new Date("2023-10-15"),
    artist_name: "Miguel Torres",
    instagram_handle: "@miguel_geometric",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$120.000-200.000",
    duration_hours: 1.5,
    difficulty: "Fácil",
    body_part: "Muñeca",
    size: "Pequeño",
  },
  {
    id: 28,
    artist_id: 4,
    title: "Elefante Ornamental",
    description: "Elefante decorado con patrones ornamentales blackwork",
    image_url: "/elefante.jpg?height=600&width=400",
    category: "Blackwork",
    tags: ["elefante", "ornamental", "decorativo", "sabiduría", "fuerza"],
    created_at: new Date("2023-10-10"),
    artist_name: "Ana Vega",
    instagram_handle: "@ana_blackwork",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$450.000-700.000",
    duration_hours: 6,
    difficulty: "Difícil",
    body_part: "Pantorrilla",
    size: "Grande",
  },
  {
    id: 29,
    artist_id: 5,
    title: "Geisha Tradicional",
    description: "Geisha japonesa con kimono y maquillaje tradicional",
    image_url: "/geisha.jpg?height=600&width=400",
    category: "Japonés",
    tags: ["geisha", "kimono", "tradicional", "elegancia", "cultura"],
    created_at: new Date("2023-10-05"),
    artist_name: "Diego Morales",
    instagram_handle: "@diego_japanese",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$700.000-1.000.000",
    duration_hours: 8,
    difficulty: "Experto",
    body_part: "Espalda",
    size: "Grande",
  },
  {
    id: 30,
    artist_id: 6,
    title: "Luna Creciente",
    description: "Luna creciente con flores fine line alrededor",
    image_url: "/luna.jpg?height=600&width=400",
    category: "Fine Line",
    tags: ["luna", "creciente", "flores", "místico", "femenino"],
    created_at: new Date("2023-09-30"),
    artist_name: "Luna Castillo",
    instagram_handle: "@luna_fineline",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$250.000-400.000",
    duration_hours: 3,
    difficulty: "Medio",
    body_part: "Espalda baja",
    size: "Mediano",
  },

  // Continúo agregando más trabajos para llegar a 60+...
  {
    id: 31,
    artist_id: 1,
    title: "Pantera Negra",
    description: "Pantera negra realista con ojos amarillos intensos",
    image_url: "/pantera.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["pantera", "negra", "ojos", "amarillos", "felino"],
    created_at: new Date("2023-09-25"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$750.000-1.100.000",
    duration_hours: 7,
    difficulty: "Experto",
    body_part: "Muslo",
    size: "Grande",
  },
  {
    id: 32,
    artist_id: 2,
    title: "Daga y Rosa",
    description: "Daga atravesando rosa en estilo tradicional",
    image_url: "/daga.jpg?height=600&width=400",
    category: "Tradicional",
    tags: ["daga", "rosa", "atravesando", "dolor", "belleza"],
    created_at: new Date("2023-09-20"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$300.000-450.000",
    duration_hours: 4,
    difficulty: "Medio",
    body_part: "Antebrazo",
    size: "Mediano",
  },
  {
    id: 33,
    artist_id: 3,
    title: "Hexágonos Conectados",
    description: "Patrón de hexágonos interconectados geométrico",
    image_url: "/hexagonos.jpg?height=600&width=400",
    category: "Geométrico",
    tags: ["hexágonos", "conectados", "patrón", "estructura", "red"],
    created_at: new Date("2023-09-15"),
    artist_name: "Miguel Torres",
    instagram_handle: "@miguel_geometric",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$350.000-550.000",
    duration_hours: 4,
    difficulty: "Medio",
    body_part: "Brazo",
    size: "Mediano",
  },
  {
    id: 34,
    artist_id: 4,
    title: "Cráneo Ornamental",
    description: "Cráneo decorado con patrones ornamentales detallados",
    image_url: "/craneo.jpg?height=600&width=400",
    category: "Blackwork",
    tags: ["cráneo", "ornamental", "decorativo", "muerte", "arte"],
    created_at: new Date("2023-09-10"),
    artist_name: "Ana Vega",
    instagram_handle: "@ana_blackwork",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$400.000-650.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Pantorrilla",
    size: "Grande",
  },
  {
    id: 35,
    artist_id: 5,
    title: "Oni Mask",
    description: "Máscara oni japonesa con detalles terroríficos",
    image_url: "/onii.jpg?height=600&width=400",
    category: "Japonés",
    tags: ["oni", "máscara", "demonio", "terror", "folclore"],
    created_at: new Date("2023-09-05"),
    artist_name: "Diego Morales",
    instagram_handle: "@diego_japanese",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$500.000-750.000",
    duration_hours: 6,
    difficulty: "Difícil",
    body_part: "Hombro",
    size: "Grande",
  },
  {
    id: 36,
    artist_id: 6,
    title: "Pluma Acuarela",
    description: "Pluma con efecto acuarela y colores degradados",
    image_url: "/pluma.jpg?height=600&width=400",
    category: "Acuarela",
    tags: ["pluma", "acuarela", "degradado", "colores", "libertad"],
    created_at: new Date("2023-08-30"),
    artist_name: "Luna Castillo",
    instagram_handle: "@luna_fineline",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$200.000-350.000",
    duration_hours: 3,
    difficulty: "Medio",
    body_part: "Costilla",
    size: "Mediano",
  },

  // Más trabajos para completar la colección...
  {
    id: 37,
    artist_id: 1,
    title: "Ciervo Majestuoso",
    description: "Ciervo con cornamenta detallada en bosque",
    image_url: "/ciervo.jpg?height=600&width=400",
    category: "Realismo",
    tags: ["ciervo", "cornamenta", "bosque", "naturaleza", "majestuoso"],
    created_at: new Date("2023-08-25"),
    artist_name: "Carlos Mendoza",
    instagram_handle: "@carlos_ink",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$650.000-950.000",
    duration_hours: 7,
    difficulty: "Difícil",
    body_part: "Espalda",
    size: "Grande",
  },
  {
    id: 38,
    artist_id: 2,
    title: "Sirena Pin-up",
    description: "Sirena estilo pin-up con colores oceánicos",
    image_url: "/sirenaa.jpg?height=600&width=400",
    category: "Neo-tradicional",
    tags: ["sirena", "pin-up", "océano", "colores", "fantasía"],
    created_at: new Date("2023-08-20"),
    artist_name: "Sofia Rodriguez",
    instagram_handle: "@sofia_tattoos",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$600.000-900.000",
    duration_hours: 7,
    difficulty: "Difícil",
    body_part: "Muslo",
    size: "Grande",
  },
  {
    id: 39,
    artist_id: 3,
    title: "Laberinto Geométrico",
    description: "Laberinto complejo con múltiples caminos",
    image_url: "/laberinto.jpg?height=600&width=400",
    category: "Geométrico",
    tags: ["laberinto", "complejo", "caminos", "decisiones", "vida"],
    created_at: new Date("2023-08-15"),
    artist_name: "Miguel Torres",
    instagram_handle: "@miguel_geometric",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$400.000-600.000",
    duration_hours: 5,
    difficulty: "Difícil",
    body_part: "Espalda",
    size: "Grande",
  },
  {
    id: 40,
    artist_id: 4,
    title: "Mandala Espalda Completa",
    description: "Mandala gigante que cubre toda la espalda",
    image_url: "/mandalaa.jpg?height=600&width=400",
    category: "Blackwork",
    tags: ["mandala", "espalda", "gigante", "completa", "impresionante"],
    created_at: new Date("2023-08-10"),
    artist_name: "Ana Vega",
    instagram_handle: "@ana_blackwork",
    artist_image: "/placeholder.svg?height=400&width=400",
    price_range: "$1.200.000-1.800.000",
    duration_hours: 15,
    difficulty: "Experto",
    body_part: "Espalda completa",
    size: "Extra Grande",
  },
]

export const mockGallery: (GalleryItem & { artist_name?: string })[] = [
  {
    id: 1,
    title: "León Majestuoso",
    description: "Obra maestra del realismo animal",
    image_url: "/Leon.jpg?height=500&width=500",
    artist_id: 1,
    category: "Realismo",
    tags: ["realismo", "león", "animal"],
    featured: true,
    created_at: new Date("2023-12-01"),
    artist_name: "Carlos Mendoza",
  },
  {
    id: 2,
    title: "Calavera Mexicana",
    description: "Explosión de colores tradicionales mexicanos",
    image_url: "/calabera.jpg?height=500&width=500",
    artist_id: 2,
    category: "Neo-tradicional",
    tags: ["calavera", "mexicana", "colores"],
    featured: true,
    created_at: new Date("2023-12-03"),
    artist_name: "Sofia Rodriguez",
  },
  {
    id: 3,
    title: "Mandala Sagrado",
    description: "Precisión geométrica perfecta",
    image_url: "/mandalaa.jpg?height=500&width=500",
    artist_id: 3,
    category: "Geométrico",
    tags: ["mandala", "geométrico", "sagrado"],
    featured: true,
    created_at: new Date("2023-12-06"),
    artist_name: "Miguel Torres",
  },
  {
    id: 4,
    title: "Blackwork Perfecto",
    description: "Técnica blackwork en su máxima expresión",
    image_url: "/perfecto.jpg?height=500&width=500",
    artist_id: 4,
    category: "Blackwork",
    tags: ["blackwork", "perfecto", "técnica"],
    featured: true,
    created_at: new Date("2023-12-04"),
    artist_name: "Ana Vega",
  },
  {
    id: 5,
    title: "Dragón Épico",
    description: "Dragón japonés que cobra vida",
    image_url: "/epico.jpg?height=500&width=500",
    artist_id: 5,
    category: "Japonés",
    tags: ["dragón", "japonés", "épico"],
    featured: true,
    created_at: new Date("2023-12-02"),
    artist_name: "Diego Morales",
  },
  {
    id: 6,
    title: "Flores Delicadas",
    description: "Fine line en su máxima delicadeza",
    image_url: "/delicadas.jpg?height=500&width=500",
    artist_id: 6,
    category: "Fine Line",
    tags: ["flores", "delicadas", "fine line"],
    featured: true,
    created_at: new Date("2023-12-07"),
    artist_name: "Luna Castillo",
  },
]

export const mockTestimonials: (Testimonial & { artist_name?: string })[] = [
  {
    id: 1,
    client_name: "Ana García",
    rating: 5,
    comment:
      "Carlos es un maestro del realismo. Mi león quedó increíble, cada detalle es perfecto. La experiencia fue profesional desde el primer momento.",
    artist_id: 1,
    featured: true,
    created_at: new Date("2023-12-01"),
    artist_name: "Carlos Mendoza",
  },
  {
    id: 2,
    client_name: "Roberto Silva",
    rating: 5,
    comment:
      "Sofia tiene un talento único para los colores. Mi calavera mexicana es una obra de arte que recibo elogios constantemente.",
    artist_id: 2,
    featured: true,
    created_at: new Date("2023-11-28"),
    artist_name: "Sofia Rodriguez",
  },
  {
    id: 3,
    client_name: "María López",
    rating: 5,
    comment:
      "Miguel creó un mandala perfecto para mí. Su precisión geométrica es impresionante, cada línea está exactamente donde debe estar.",
    artist_id: 3,
    featured: true,
    created_at: new Date("2023-11-25"),
    artist_name: "Miguel Torres",
  },
  {
    id: 4,
    client_name: "Patricia Vega",
    rating: 5,
    comment:
      "Ana es una maestra del blackwork. Mi diseño ornamental es único y la técnica es impecable. Totalmente recomendada.",
    artist_id: 4,
    featured: true,
    created_at: new Date("2023-11-22"),
    artist_name: "Ana Vega",
  },
  {
    id: 5,
    client_name: "Fernando Castro",
    rating: 5,
    comment:
      "Diego capturó perfectamente la esencia del arte japonés. Mi dragón es épico y la atención al detalle es extraordinaria.",
    artist_id: 5,
    featured: true,
    created_at: new Date("2023-11-20"),
    artist_name: "Diego Morales",
  },
  {
    id: 6,
    client_name: "Carmen Ruiz",
    rating: 5,
    comment:
      "Luna tiene una delicadeza única en sus trazos. Mis flores fine line son elegantes y femeninas, exactamente lo que quería.",
    artist_id: 6,
    featured: true,
    created_at: new Date("2023-11-18"),
    artist_name: "Luna Castillo",
  },
]

export const mockAppointments: (Appointment & { artist_name?: string })[] = [
  {
    id: 1,
    client_name: "Juan Pérez",
    client_email: "juan@email.com",
    client_phone: "+1-555-1001",
    artist_id: 1,
    appointment_date: "2024-01-15",
    appointment_time: "10:00:00",
    tattoo_description: "Retrato realista de mascota",
    estimated_duration: 4,
    estimated_price: 800.0,
    status: "confirmed",
    notes: "Primera sesión",
    created_at: new Date("2023-12-01"),
    updated_at: new Date("2023-12-01"),
    artist_name: "Carlos Mendoza",
  },
  {
    id: 2,
    client_name: "Laura Martín",
    client_email: "laura@email.com",
    client_phone: "+1-555-1002",
    artist_id: 2,
    appointment_date: "2024-01-16",
    appointment_time: "14:00:00",
    tattoo_description: "Rosa tradicional en antebrazo",
    estimated_duration: 2,
    estimated_price: 300.0,
    status: "pending",
    created_at: new Date("2023-12-02"),
    updated_at: new Date("2023-12-02"),
    artist_name: "Sofia Rodriguez",
  },
]

// Datos adicionales para enriquecer la experiencia
export const mockBlogPosts = [
  {
    id: 1,
    title: "Cuidados Post-Tatuaje: Guía Completa",
    excerpt: "Todo lo que necesitas saber para cuidar tu nuevo tatuaje correctamente",
    content: "Los primeros días después de hacerte un tatuaje son cruciales...",
    author: "Equipo Inskpire",
    date: new Date("2023-12-01"),
    category: "Cuidados",
    image: "/cuidado.jpg?height=300&width=500",
  },
  {
    id: 2,
    title: "Tendencias en Tatuajes 2024",
    excerpt: "Descubre los estilos que marcarán tendencia este año",
    content: "El mundo del tatuaje evoluciona constantemente...",
    author: "Sofia Rodriguez",
    date: new Date("2023-11-28"),
    category: "Tendencias",
    image: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 3,
    title: "Preparación para tu Primer Tatuaje",
    excerpt: "Consejos esenciales para quienes se tatúan por primera vez",
    content: "Decidir hacerse el primer tatuaje es emocionante...",
    author: "Carlos Mendoza",
    date: new Date("2023-11-25"),
    category: "Consejos",
    image: "/placeholder.svg?height=300&width=500",
  },
]

export const mockFAQs = [
  {
    id: 1,
    question: "¿Cuánto tiempo tarda en sanar un tatuaje?",
    answer:
      "Un tatuaje típicamente tarda entre 2-4 semanas en sanar completamente. Los primeros 3-5 días son los más críticos para el cuidado.",
    category: "Cuidados",
  },
  {
    id: 2,
    question: "¿Cuál es el precio promedio de un tatuaje?",
    answer:
      "Los precios varían según el tamaño, complejidad y artista. Nuestros precios van desde $120 para diseños pequeños hasta $2000+ para piezas grandes.",
    category: "Precios",
  },
  {
    id: 3,
    question: "¿Puedo traer mi propio diseño?",
    answer:
      "¡Por supuesto! Nuestros artistas pueden trabajar con tu diseño o modificarlo para adaptarlo mejor a tu anatomía y preferencias.",
    category: "Diseño",
  },
  {
    id: 4,
    question: "¿Qué debo hacer antes de mi cita?",
    answer: "Asegúrate de comer bien, estar hidratado, evitar alcohol 24h antes, y traer una identificación válida.",
    category: "Preparación",
  },
]
